In [1]:
import numpy as np

In [2]:
dir_path = "/Users/ecem/Desktop/gyrocardiogram/data"

In [3]:
x = np.load(dir_path + "/gyro_x.npy", allow_pickle= True)
y = np.load(dir_path + "/gyro_y.npy", allow_pickle= True)
z = np.load(dir_path + "/gyro_z.npy", allow_pickle= True)

In [4]:
print(x.shape)
print(y.shape)
print(z.shape)

(100,)
(100,)
(100,)


In [5]:
diseased = np.stack((x, y, z), axis = 1)
print(diseased.shape)

(100, 3)


In [6]:
x[0]

array([0.51908397, 0.5648855 , 0.51908397, ..., 0.6259542 , 1.14503817,
       0.73282443])

In [7]:
diseased[0][0]

array([0.51908397, 0.5648855 , 0.51908397, ..., 0.6259542 , 1.14503817,
       0.73282443])

In [8]:
def splitter(array, slicing_point = 10000, duration = 10, sampling_rate = 256):
    wanted_npts = int(sampling_rate * duration) 
    npts = int(array[0].shape[0] - 10000)
    lenght = npts // wanted_npts
    remainder = int(np.around((((npts / wanted_npts - lenght)) * wanted_npts), 0))
    
    print("{},".format(lenght))
    
    return [np.array_split(array[0][slicing_point + remainder:],lenght),
           np.array_split(array[1][slicing_point + remainder:],lenght),
           np.array_split(array[2][slicing_point + remainder:],lenght)]
    

In [9]:
def merger(array, slicing_point = 10000, duration = 10):
    _x, _y, _z  = [], [], []

    for i in range(len(array)):
        a, b, c = splitter(array[i], slicing_point = slicing_point, duration = duration, sampling_rate = 256)
        _x = _x + a
        _y = _y + b
        _z = _z + c


        
    return [_x,_y,_z]

In [10]:
_x, _y, _z = merger(diseased, duration = 10)

44,
55,
55,
49,
43,
37,
37,
49,
49,
43,
49,
61,
49,
43,
49,
49,
49,
58,
53,
43,
43,
43,
43,
37,
49,
49,
50,
47,
53,
44,
52,
44,
55,
57,
45,
48,
40,
42,
43,
48,
46,
36,
38,
41,
39,
37,
38,
48,
42,
57,
41,
38,
42,
44,
43,
47,
42,
39,
41,
44,
45,
37,
41,
41,
43,
46,
47,
35,
43,
42,
33,
33,
32,
29,
37,
30,
32,
27,
27,
26,
26,
27,
27,
29,
29,
30,
31,
27,
27,
43,
27,
26,
26,
11,
11,
11,
11,
11,
11,
11,


In [11]:
len(_x)

3917

In [12]:
type(_x)

list

In [13]:
type(_x[0][0])

numpy.float64

In [14]:
_x_ = np.array(_x)

In [15]:
for i in range(_x_.shape[0]):
    print(len(_x_[i]))

2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


In [16]:
for i in range(10):
    print(_x_[i][:5])

[0.88549618 0.65648855 0.5648855  0.73282443 0.76335878]
[0.64122137 0.7480916  0.6870229  0.71755725 0.30534351]
[ 0.16793893  0.53435115  0.25954198  0.15267176 -0.16793893]
[0.18320611 0.09160305 0.38167939 0.27480916 0.48854962]
[-0.10687023  0.15267176 -0.07633588 -0.03053435  0.04580153]
[0.61068702 0.53435115 0.7480916  0.6870229  0.61068702]
[-0.0610687  -0.1221374  -0.10687023  0.25954198  0.21374046]
[ 0.47328244  0.47328244 -0.0610687  -0.53435115 -1.38931298]
[-0.18320611 -0.13740458 -0.25954198 -0.42748092 -0.42748092]
[0.13740458 0.22900763 0.25954198 0.53435115 0.15267176]


In [17]:
_y_ = np.array(_y)

In [18]:
for i in range(_y_.shape[0]):
    print(len(_y_[i]))

2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


In [19]:
for i in range(10):
    print(_y_[i][:5])

[ 0.04580153 -0.24427481 -0.70229008 -0.6259542  -0.09160305]
[ 0.39694656  0.47328244  0.18320611 -0.18320611 -0.0610687 ]
[0.10687023 0.32061069 0.71755725 0.1221374  0.19847328]
[ 0.38167939 -0.04580153  0.16793893  0.41221374  0.27480916]
[-0.22900763 -0.09160305 -0.42748092 -0.10687023  0.09160305]
[0.6259542  0.70229008 0.48854962 0.24427481 0.44274809]
[ 0.22900763 -0.01526718  0.16793893  0.22900763  0.19847328]
[ 1.41984733  0.97709924 -0.10687023 -0.50381679 -0.59541985]
[0.35114504 0.10687023 0.04580153 0.22900763 0.24427481]
[-0.61068702 -0.48854962 -0.5648855  -0.70229008 -0.61068702]


In [20]:
_z_ = np.array(_z)

In [21]:
for i in range(_z_.shape[0]):
    print(len(_z_[i]))

2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


In [22]:
for i in range(10):
    print(_z_[i][:5])

[ 0.29007634  0.1221374   0.16793893 -0.09160305  0.22900763]
[0.35114504 0.30534351 0.29007634 0.35114504 0.32061069]
[0.15267176 0.44274809 0.36641221 0.53435115 0.53435115]
[0.35114504 0.27480916 0.24427481 0.22900763 0.38167939]
[0.13740458 0.32061069 0.03053435 0.24427481 0.25954198]
[0.41221374 0.45801527 0.65648855 0.44274809 0.0610687 ]
[0.35114504 0.32061069 0.16793893 0.21374046 0.19847328]
[ 0.61068702  0.30534351  0.30534351 -0.0610687  -0.71755725]
[0.29007634 0.39694656 0.47328244 0.5648855  0.41221374]
[ 0.01526718 -0.09160305 -0.16793893  0.21374046 -0.04580153]


In [23]:
type(_x_)

numpy.ndarray

In [24]:
type(_y_)

numpy.ndarray

In [25]:
type(_z_)

numpy.ndarray

In [26]:
_x_.shape

(3917, 2560)

In [27]:
_y_.shape

(3917, 2560)

In [28]:
_z_.shape

(3917, 2560)

In [29]:
np.save("/Users/ecem/Desktop/gyrocardiogram/phase2/10sec_x_splitted", _x_, allow_pickle= True)
np.save("/Users/ecem/Desktop/gyrocardiogram/phase2/10sec_y_splitted", _y_, allow_pickle= True)
np.save("/Users/ecem/Desktop/gyrocardiogram/phase2/10sec_z_splitted", _z_, allow_pickle= True)