In [1]:
import numpy as np

In [2]:
dir_path = "/Users/ecem/Desktop/gyrocardiogram/data"

In [3]:
x = np.load(dir_path + "/scg_x.npy", allow_pickle= True)
y = np.load(dir_path + "/scg_y.npy", allow_pickle= True)
z = np.load(dir_path + "/scg_z.npy", allow_pickle= True)

In [4]:
print(x.shape)
print(y.shape)
print(z.shape)

(100,)
(100,)
(100,)


In [5]:
diseased = np.stack((x, y, z), axis = 1)
print(diseased.shape)

(100, 3)


In [6]:
x[0]

array([1.95652174, 1.95652174, 1.98913043, ..., 0.7826087 , 0.79347826,
       0.80434783])

In [7]:
diseased[0][0]

array([1.95652174, 1.95652174, 1.98913043, ..., 0.7826087 , 0.79347826,
       0.80434783])

In [8]:
def splitter(array, slicing_point = 10000, duration = 10, sampling_rate = 256):
    wanted_npts = int(sampling_rate * duration) 
    npts = int(array[0].shape[0] - 10000)
    lenght = npts // wanted_npts
    remainder = int(np.around((((npts / wanted_npts - lenght)) * wanted_npts), 0))
    
    print("{},".format(lenght))
    
    return [np.array_split(array[0][slicing_point + remainder:],lenght),
           np.array_split(array[1][slicing_point + remainder:],lenght),
           np.array_split(array[2][slicing_point + remainder:],lenght)]
    

In [9]:
def merger(array, slicing_point = 10000, duration = 10):
    _x, _y, _z  = [], [], []

    for i in range(len(array)):
        a, b, c = splitter(array[i], slicing_point = slicing_point, duration = duration, sampling_rate = 256)
        _x = _x + a
        _y = _y + b
        _z = _z + c


        
    return [_x,_y,_z]

In [10]:
_x, _y, _z = merger(diseased, duration = 10)

44,
55,
55,
49,
43,
37,
37,
49,
49,
43,
49,
61,
49,
43,
49,
49,
49,
58,
53,
43,
43,
43,
43,
37,
49,
49,
50,
47,
53,
44,
52,
44,
55,
57,
45,
48,
40,
42,
43,
48,
46,
36,
38,
41,
39,
37,
38,
48,
42,
57,
41,
38,
42,
44,
43,
47,
42,
39,
41,
44,
45,
37,
41,
41,
43,
46,
47,
35,
43,
42,
33,
33,
32,
29,
37,
30,
32,
27,
27,
26,
26,
27,
27,
29,
29,
30,
31,
27,
27,
43,
27,
116,
116,
56,
57,
57,
57,
56,
55,
56,


In [11]:
len(_x)

4414

In [12]:
type(_x)

list

In [13]:
type(_x[0][0])

numpy.float64

In [14]:
_x_ = np.array(_x)

In [15]:
#sanity check
for i in range(_x_.shape[0]):
    print(len(_x_[i]))

2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


In [16]:
for i in range(4):
    print(_x_[i][:20])

[1.80434783 1.80434783 1.81521739 1.82608696 1.81521739 1.82608696
 1.79347826 1.77173913 1.77173913 1.7826087  1.80434783 1.80434783
 1.80434783 1.81521739 1.81521739 1.81521739 1.82608696 1.83695652
 1.82608696 1.81521739]
[1.83695652 1.81521739 1.82608696 1.82608696 1.83695652 1.84782609
 1.85869565 1.85869565 1.84782609 1.83695652 1.80434783 1.80434783
 1.82608696 1.83695652 1.84782609 1.85869565 1.83695652 1.82608696
 1.82608696 1.83695652]
[1.84782609 1.83695652 1.80434783 1.7826087  1.76086957 1.7826087
 1.79347826 1.82608696 1.80434783 1.80434783 1.80434783 1.81521739
 1.81521739 1.82608696 1.84782609 1.83695652 1.83695652 1.81521739
 1.84782609 1.85869565]
[1.85869565 1.85869565 1.88043478 1.88043478 1.88043478 1.85869565
 1.85869565 1.86956522 1.86956522 1.83695652 1.84782609 1.82608696
 1.84782609 1.83695652 1.83695652 1.83695652 1.82608696 1.82608696
 1.83695652 1.81521739]


In [17]:
_y_ = np.array(_y)

In [18]:
for i in range(_y_.shape[0]):
    print(len(_y_[i]))

2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


In [19]:
for i in range(4):
    print(_y_[i][:20])

[2.04347826 2.0326087  2.0326087  2.0326087  2.0326087  2.05434783
 2.06521739 2.08695652 2.07608696 2.08695652 2.10869565 2.08695652
 2.06521739 2.05434783 2.02173913 2.01086957 1.98913043 2.
 2.         1.97826087]
[2.04347826 2.04347826 2.0326087  2.0326087  2.02173913 2.
 2.01086957 2.02173913 2.0326087  2.04347826 2.05434783 2.06521739
 2.06521739 2.08695652 2.07608696 2.05434783 2.0326087  2.02173913
 2.01086957 2.        ]
[2.02173913 2.0326087  2.05434783 2.04347826 2.04347826 2.05434783
 2.05434783 2.07608696 2.05434783 2.04347826 1.98913043 2.
 1.98913043 1.98913043 1.97826087 1.98913043 1.97826087 1.97826087
 1.98913043 1.9673913 ]
[1.98913043 1.97826087 1.9673913  1.98913043 1.98913043 1.9673913
 1.98913043 1.97826087 1.98913043 1.97826087 2.01086957 2.01086957
 2.02173913 2.02173913 2.01086957 2.0326087  2.04347826 2.0326087
 2.04347826 2.04347826]


In [20]:
_z_ = np.array(_z)

In [21]:
for i in range(_z_.shape[0]):
    print(len(_z_[i]))

2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560
2560


In [22]:
for i in range(10):
    print(_z_[i][:5])

[10.84782609 10.85869565 10.85869565 10.80434783 10.82608696]
[10.88043478 10.88043478 10.88043478 10.85869565 10.90217391]
[10.80434783 10.83695652 10.88043478 10.90217391 10.89130435]
[10.86956522 10.88043478 10.88043478 10.88043478 10.89130435]
[10.86956522 10.88043478 10.88043478 10.85869565 10.85869565]
[10.88043478 10.90217391 10.88043478 10.86956522 10.85869565]
[10.86956522 10.86956522 10.88043478 10.88043478 10.88043478]
[10.92391304 10.92391304 10.86956522 10.82608696 10.7826087 ]
[10.83695652 10.81521739 10.80434783 10.81521739 10.84782609]
[10.88043478 10.84782609 10.86956522 10.88043478 10.88043478]


In [23]:
type(_x_)

numpy.ndarray

In [24]:
type(_y_)

numpy.ndarray

In [25]:
type(_z_)

numpy.ndarray

In [26]:
_x_.shape

(4414, 2560)

In [27]:
_y_.shape

(4414, 2560)

In [28]:
_z_.shape

(4414, 2560)

In [29]:
np.save("/Users/ecem/Desktop/gyrocardiogram/phase2/scg_10sec_x_splitted", _x_, allow_pickle= True)
np.save("/Users/ecem/Desktop/gyrocardiogram/phase2/scg_10sec_y_splitted", _y_, allow_pickle= True)
np.save("/Users/ecem/Desktop/gyrocardiogram/phase2/scg_10sec_z_splitted", _z_, allow_pickle= True)