## Imports:

In [1]:
import scipy.io
import os
import pandas
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as plt_lab
import matplotlib.gridspec as gridspec
import obspy
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Load data:
We are going to use this data to plot spectograms of SCG signals. 

In [3]:
path = "/Users/ecem/Desktop/gyrocardiogram/data"

In [4]:
x = np.load(path + "/scg_x.npy", allow_pickle= True)
y = np.load(path + "/scg_y.npy", allow_pickle= True)
z = np.load(path + "/scg_z.npy", allow_pickle= True)

In [5]:
x.shape

(100,)

## Load csv and create two seperate dataframe:
We are going to use heart dataframe to differentiate healty people from the people with diaseaes. Data's of healty people will be stored in the healty dataset while diseased people will be in diseased dataset.

In [6]:
heart = pd.read_excel("/Users/ecem/Desktop/seismocardiogram/data/diseased-dataset/Summary_Pub_Deidentified.xlsx")
df = heart.copy().fillna(0)

I have dropped some columns because they didnt have much information. ????????

In [7]:
df.drop(["Mitral valve Peak velocity (m/sec)",
         "Mitral valve Mean gradient(mmHg)", 
         "Echo available",
        "Date of collection",
        "Date of echo"], 
        inplace = True, axis = 1)
df.drop(df.tail(1).index,inplace=True)

## only without TR

In [8]:
idx = np.where(df['moderate or greater TR'] != 1.0)


In [9]:
idx

(array([ 0,  1,  2,  4,  5,  6,  7,  8, 12, 14, 17, 19, 21, 25, 26, 27, 28,
        29, 31, 32, 36, 37, 38, 39, 40, 43, 44, 45, 46, 49, 50, 52, 54, 58,
        60, 62, 64, 65, 68, 71, 73, 76, 78, 79, 80, 81, 82, 83, 84, 85, 87,
        88, 89, 92, 94, 95, 96, 97, 98, 99]),)

## only with s

In [10]:
idx_s  = np.where(((df['Moderate or greater MS'] == 1.0 ) | (df['Moderate or greater AS'] == 1.0))
         & (df['Moderate or greater MR'] == 0.0 )
         & (df['Moderate or greater AR'] == 0.0 ))

In [11]:
idx_s

(array([ 8, 22, 23, 24, 28, 41, 44, 51, 62, 67, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79, 80, 81, 83, 84, 85, 86, 87, 88, 91, 92, 93, 95, 96, 97,
        98, 99]),)

In [12]:
idx_s[0].shape

(36,)

## only with regurgitation

In [13]:
idx_r  = np.where((df['Moderate or greater MS'] == 0.0 ) 
            &((df['Moderate or greater MR'] == 1.0 )| (df['Moderate or greater AR'] == 1.0 )) 
            &(df['Moderate or greater AS'] == 0.0))
idx_r[0]

array([ 0,  2,  3,  9, 10, 11, 12, 13, 15, 17, 18, 19, 20, 21, 25, 26, 27,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 45, 47, 50, 54, 55, 56, 57,
       58, 59, 60, 61, 63, 64, 65, 66, 68, 69])

In [14]:
idx_r[0].shape

(44,)

## split the dataframe

In [15]:
diseased_s = df.loc[idx_s]

In [16]:
diseased_s

Patient ID     Start  Duration  Sampling rate(Hz)   Age Gender  \
8       CP-09  00:00:50  00:07:50         256.000000  46.0      F   
22      CP-23  00:00:26  00:07:23         256.000000  61.0      M   
23      CP-24  00:00:29  00:06:22         256.000000  53.0      F   
24      CP-25  00:00:46  00:08:00         256.000000  73.0      M   
28      CP-29  00:01:21  00:07:40         256.000000  32.0      M   
41      CP-42  00:00:39  00:05:51         256.000000  72.0      F   
44      CP-45  00:00:33  00:06:19         256.000000  70.0      M   
51      CP-52  00:00:28  00:06:28         256.000000  61.0      F   
62      CP-63  00:00:51  00:06:31         256.000000  53.0      F   
67      CP-68  00:00:29  00:05:31         256.000000  65.0      M   
70      UP-01  00:00:00  00:06:08         256.000000  89.0      M   
71      UP-02  00:00:00  00:06:10         256.000000  89.0      M   
72      UP-03  00:00:00  00:06:01         256.000000  96.0      M   
73      UP-04  00:00:00  00:05:36         256.000000  84.0      M   
74      UP-05  00:00:15  00:06:35         256.000000  70.0      F   
75      UP-06  00:00:00  00:05:39         256.000000  90.0      F   
76      UP-07  00:00:00  00:06:03         256.000000  84.0      M   
77      UP-08  00:00:00  00:05:11         256.000000  95.0      F   
78      UP-09  00:00:00  00:05:15         256.000000  89.0      M   
79      UP-10  00:00:00  00:05:02         256.000000  80.0      F   
80      UP-11  00:00:00  00:05:06         256.000000  68.0      M   
81      UP-12  00:00:00  00:05:10         256.000000  79.0      F   
83      UP-14  00:00:00  00:05:38         256.000000  85.0      F   
84      UP-15  00:00:00  00:05:34         256.000000  84.0      F   
85      UP-16  00:00:00  00:05:44         256.000000  97.0      M   
86      UP-17  00:00:00  00:05:54         256.000000  80.0      M   
87      UP-18  00:00:00  00:05:09         256.000000  90.0      F   
88      UP-19  00:00:00  00:05:17         256.000000  78.0      M   
91      UP-22  00:00:00  00:10:03         512.000000  77.0      F   
92      UP-23  00:00:00  00:09:59         512.041667  84.0      F   
93      UP-24  00:00:00  00:05:00         512.083333  80.0      F   
95      UP-26  00:00:00  00:05:08         512.166667  80.0      M   
96      UP-27  00:00:00  00:05:05         512.208333  82.0      M   
97      UP-28  00:00:00  00:05:02         512.250000  71.0      M   
98      UP-29  00:00:00  00:04:58         512.291667  80.0      M   
99      UP-30  00:00:00  00:04:59         512.333333  71.0      M   

    Height (cm)  Weight (kg)  History of MI  History of CABG  ...  TAPSE  \
8         155.0         59.0            0.0              0.0  ...   19.0   
22        176.0         65.0            0.0              0.0  ...   24.0   
23        162.0         54.0            0.0              0.0  ...   18.0   
24        170.0         80.0            0.0              0.0  ...   20.0   
28        172.0         71.0            0.0              0.0  ...   16.0   
41        150.0         50.0            0.0              0.0  ...   16.0   
44        170.0         80.0            0.0              0.0  ...   21.0   
51        154.0         54.0            0.0              0.0  ...   17.0   
62        158.0         60.0            0.0              0.0  ...   18.0   
67        170.0         62.0            1.0              0.0  ...   12.0   
70        154.9         49.0            0.0              1.0  ...    0.0   
71        170.2         82.0            1.0              1.0  ...    0.0   
72        162.5         66.0            0.0              1.0  ...    0.0   
73        152.4         65.0            0.0              1.0  ...    0.0   
74        162.5         79.0            0.0              1.0  ...    0.0   
75        160.0         48.0            1.0              1.0  ...    0.0   
76        162.5         79.0            0.0              1.0  ...    0.0   
77        152.4         44.0            0.0              1.0  ...    0.0   
78   

In [17]:
diseased_r = df.loc[idx_r]
diseased_r

Patient ID     Start  Duration  Sampling rate(Hz)   Age Gender  \
0       CP-01  00:00:08  00:07:42              256.0  59.0      M   
2       CP-03  00:00:40  00:08:50              256.0  70.0      M   
3       CP-04  00:00:02  00:08:30              256.0  56.0      M   
9       CP-10  00:00:25  00:07:25              256.0  54.0      F   
10      CP-11  00:00:38  00:08:08              256.0  71.0      F   
11      CP-12  00:00:42  00:09:55              256.0  54.0      M   
12      CP-13  00:00:37  00:08:03              256.0  29.0      M   
13      CP-14  00:00:26  00:07:18              256.0  72.0      M   
15      CP-16  00:00:40  00:08:00              256.0  77.0      M   
17      CP-18  00:00:37  00:08:28              256.0  77.0      M   
18      CP-19  00:02:04  00:07:00              256.0  60.0      F   
19      CP-20  00:00:40  00:07:06              256.0  54.0      M   
20      CP-21  00:00:30  00:07:15              256.0  58.0      M   
21      CP-22  00:00:29  00:07:19              256.0  64.0      M   
25      CP-26  00:00:27  00:08:25              256.0  72.0      M   
26      CP-27  00:00:38  00:08:00              256.0  74.0      M   
27      CP-28  00:00:21  00:07:51              256.0  74.0      F   
31      CP-32  00:00:44  00:07:00              256.0  66.0      F   
32      CP-33  00:00:57  00:08:08              256.0  66.0      F   
33      CP-34  00:01:26  00:08:10              256.0  58.0      F   
34      CP-35  00:01:00  00:06:18              256.0  55.0      M   
35      CP-36  00:01:52  00:06:24              256.0  73.0      F   
36      CP-37  00:00:28  00:06:29              256.0  54.0      M   
37      CP-38  00:00:30  00:06:42              256.0  59.0      M   
38      CP-39  00:00:44  00:06:55              256.0  39.0      M   
39      CP-40  00:00:45  00:07:14              256.0  52.0      M   
43      CP-44  00:00:25  00:06:52              256.0  63.0      M   
45      CP-46  00:00:37  00:06:10              256.0  46.0      M   
47      CP-48  00:00:48  00:07:41              256.0  73.0      M   
50      CP-51  00:00:25  00:07:00              256.0  50.0      M   
54      CP-55  00:00:00  00:07:15              256.0  65.0      M   
55      CP-56  00:00:28  00:07:31              256.0  72.0      M   
56      CP-57  00:00:27  00:06:44              256.0  79.0      M   
57      CP-58  00:00:30  00:06:33              256.0  73.0      M   
58      CP-59  00:00:27  00:06:35              256.0  57.0      F   
59      CP-60  00:00:32  00:06:53              256.0  49.0      F   
60      CP-61  00:00:26  00:07:08              256.0  68.0      F   
61      CP-62  00:00:24  00:06:22              256.0  59.0      F   
63      CP-64  00:00:48  00:06:07              256.0  57.0      M   
64      CP-65  00:00:33  00:06:25              256.0  76.0      F   
65      CP-66  00:00:25  00:06:20              256.0  59.0      M   
66      CP-67  00:00:33  00:06:49              256.0  66.0      F   
68      CP-69  00:00:21  00:07:09              256.0  36.0      M   
69      CP-70  00:00:24  00:06:46              256.0  63.0      M   

    Height (cm)  Weight (kg)  History of MI  History of CABG  ...  TAPSE  \
0         174.0         74.0            0.0              0.0  ...   19.0   
2         167.0         84.0            0.0              0.0  ...   20.0   
3         154.0         56.0            0.0              0.0  ...   17.0   
9         164.0         68.0            0.0              0.0  ...   19.0   
10        161.0         58.0            0.0              0.0  ...   21.0   
11        170.0         70.0            0.0              0.0  ...   20.0   
12        172.0         68.5            0.0              0.0  ...   24.0   
13        175.0         80.0            0.0              0.0  ...   16.0   
15        160.0         60.0            0.0              0.0  ...   20.0   
17        170.0         80.0            0.0              0.0  ...   25.0   
18        158.0         65.0            0.0              0.0 

In [18]:
diseased_x_s, diseased_y_s, diseased_z_s = [],[],[]
diseased_x_r, diseased_y_r, diseased_z_r = [],[],[]


In [19]:
for i in range(len(diseased_s['Patient ID'].index)):
    x_ = x[diseased_s['Patient ID'].index[i]]
    y_ = y[diseased_s['Patient ID'].index[i]]
    z_ = z[diseased_s['Patient ID'].index[i]]
    
    diseased_x_s.append(x_)
    diseased_y_s.append(y_) 
    diseased_z_s.append(z_) 
del x_, y_, z_

In [20]:
stacked_diseased_s = np.stack((diseased_x_s, diseased_y_s, diseased_z_s), axis = -1)

In [21]:
print(stacked_diseased_s.shape)

(36, 3)


In [22]:
for i in range(len(diseased_r['Patient ID'].index)):
    x_ = x[diseased_r['Patient ID'].index[i]]
    y_ = y[diseased_r['Patient ID'].index[i]]
    z_ = z[diseased_r['Patient ID'].index[i]]
    
    diseased_x_r.append(x_)
    diseased_y_r.append(y_) 
    diseased_z_r.append(z_) 
del x_, y_, z_

In [23]:
stacked_diseased_r = np.stack((diseased_x_r, diseased_y_r, diseased_z_r), axis = -1)

In [24]:
print(stacked_diseased_r.shape)


(44, 3)


## save waveforms

In [25]:
np.save("/Users/ecem/Desktop/gyrocardiogram/data/diseased_scg_s", stacked_diseased_s, allow_pickle= True)
np.save("/Users/ecem/Desktop/gyrocardiogram/data/diseased_scg_r", stacked_diseased_r, allow_pickle= True)